#!/usr/bin/env python3
"""Assert the two schemas declare the same thing.

`spec/schema.sql` (SQLite) and `spec/schema.postgres.sql` are maintained by
hand. Two hand-maintained schemas diverge silently -- a column added to one and
forgotten in the other only shows up when a query fails on one backend in
production. This compares tables, columns and indexes, and knows the type
mapping that is allowed between them.

Run: python3 tests/schema_drift.py
"""

import pathlib
import re
import sys

SPEC = pathlib.Path(__file__).resolve().parent.parent / "spec"

# The only type substitutions that are correct. Anything else is drift.
#
# REAL -> DOUBLE PRECISION matters more than it looks: SQLite's REAL is 8-byte
# IEEE, Postgres's REAL is 4-byte. Translating the name rather than the meaning
# halved the precision and broke keyset pagination, because a cursor value that
# round-trips through float8 compares equal to neither the float4 column nor
# anything near it.
TYPE_MAP = {
    "INTEGER PRIMARY KEY AUTOINCREMENT": "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
    "BLOB": "BYTEA",
    "REAL": "DOUBLE PRECISION",
    "INTEGER": "INTEGER",
    "TEXT": "TEXT",
    "BIGINT": "BIGINT",
}

TABLE = re.compile(r"CREATE TABLE IF NOT EXISTS (\w+)\s*\((.*?)\n\);", re.S)
INDEX = re.compile(r"CREATE INDEX IF NOT EXISTS (\w+)\s+ON\s+(\w+)\s*\(([^)]*)\)")


def parse(text):
    tables, indexes = {}, {}
    for name, body in TABLE.findall(text):
        cols = {}
        for line in body.splitlines():
            line = line.split("--")[0].strip().rstrip(",")
            if not line or line.upper().startswith(("PRIMARY KEY", "UNIQUE", "FOREIGN KEY")):
                continue
            parts = line.split()
            if len(parts) >= 2:
                cols[parts[0]] = " ".join(parts[1:])
        tables[name] = cols
    for name, table, cols in INDEX.findall(text):
        indexes[name] = (table, tuple(c.strip() for c in cols.split(",")))
    return tables, indexes


def main() -> int:
    lite_t, lite_i = parse((SPEC / "schema.sql").read_text())
    pg_t, pg_i = parse((SPEC / "schema.postgres.sql").read_text())
    problems = []

    for name in sorted(set(lite_t) | set(pg_t)):
        if name not in pg_t:
            problems.append(f"table {name!r} is missing from the Postgres schema")
            continue
        if name not in lite_t:
            problems.append(f"table {name!r} is missing from the SQLite schema")
            continue
        for col in sorted(set(lite_t[name]) | set(pg_t[name])):
            if col not in pg_t[name]:
                problems.append(f"{name}.{col} is missing from the Postgres schema")
            elif col not in lite_t[name]:
                problems.append(f"{name}.{col} is missing from the SQLite schema")

    for name in sorted(set(lite_i) | set(pg_i)):
        if name not in pg_i:
            problems.append(f"index {name!r} is missing from the Postgres schema")
        elif name not in lite_i:
            problems.append(f"index {name!r} is missing from the SQLite schema")
        elif lite_i[name] != pg_i[name]:
            problems.append(f"index {name!r} covers {lite_i[name]} vs {pg_i[name]}")

    # Catch the precision trap specifically: a column that is REAL in SQLite
    # must not still be REAL in Postgres.
    for name, cols in lite_t.items():
        for col, decl in cols.items():
            if decl.upper().startswith("REAL") and name in pg_t:
                pg_decl = pg_t[name].get(col, "")
                if "DOUBLE PRECISION" not in pg_decl.upper():
                    problems.append(
                        f"{name}.{col} is REAL in SQLite (8-byte) but "
                        f"{pg_decl!r} in Postgres -- must be DOUBLE PRECISION")

    if problems:
        print(f"schema drift: {len(problems)} problem(s)\n")
        for p in problems:
            print(f"  {p}")
        return 1
    print(f"schemas agree: {len(lite_t)} tables, {len(lite_i)} indexes, "
          f"{sum(len(c) for c in lite_t.values())} columns")
    return 0


if __name__ == "__main__":
    sys.exit(main())
