{{- if eq (include "blurd.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blurd.fullname" . }}
  labels:
    {{- include "blurd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.dashboard.enabled .Values.dashboard.password (not .Values.dashboard.existingSecret) }}
  dashboardPassword: {{ .Values.dashboard.password | quote }}
  {{- end }}
  {{- if and (ne .Values.db.backend "sqlite") .Values.db.dsn (not .Values.db.existingSecret) }}
  dsn: {{ .Values.db.dsn | quote }}
  {{- end }}
  {{- if and (eq .Values.storage.backend "s3") .Values.storage.s3.accessKey (not .Values.storage.s3.existingSecret) }}
  s3AccessKey: {{ .Values.storage.s3.accessKey | quote }}
  s3SecretKey: {{ .Values.storage.s3.secretKey | quote }}
  {{- end }}
{{- end }}
